version: "3.2"

services:
  markdeck:
    image: "arne/markdeck-pandoc:0.31"
    volumes:
      - type: bind
        source: ./
        target: /source
        read_only: true
      - type: bind
        source: ./deck
        target: /target

  web:
    image: "arne/markdeck-liveserver:0.2"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./deck
        target: /target
    depends_on: [markdeck]

  pdf:
    image: "arne/markdeck-decktape:0.4"
    volumes:
      - type: bind
        source: ./deck
        target: /slides
    shm_size: 1G
    depends_on: [markdeck, web]

  standalone:
    image: "arne/markdeck-standalone:0.2"
    volumes:
      - type: bind
        source: ./deck
        target: /target
    depends_on: [web]

  helper:
    image: "arne/markdeck-helper:0.2"
    ports:
      - "8081:8081"

  a2sketch:
    image: "arne/a2sketch:0.7"
